### PR TITLE
collapse dirname(...)

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by cebe** [comment]
according to http://php.net/manual/en/function.dirname.php this is PHP 7 only.

**Comment by samdark** [comment]
Reverted :)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/44dd561109a0377d25b64511e50b5ca8494dac1d

**Pull request merged**
