### PR TITLE
Codeception/verify v2 update

### PR DESCRIPTION
**Pull request by TavoNiievez**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes

### CODE REVIEW

**Comment by TavoNiievez** [comment]
@samdark I added these conditionals before seeing #516 , if you have already decided to remove support for old PHP versions that would simplify the code a lot and you could go directly to Verify `^2.0`, and you could even update the other Codeception modules that are being used here.
Anyway, as is, it works for all versions of PHP.

**Comment by developedsoftware** [comment]
expect and expect_that is removed in 2.2. Should we update the tests to use verify() which I believe work fine still?

i opened this pull request but closed it #519

**Comment by TavoNiievez** [comment]
[`expect()`](https://github.com/Codeception/Verify/blob/master/docs/supported_expectations.md) still works.

**Comment by developedsoftware** [comment]
Sorry you are right / expect_that and expect_not have been removed from 2.2 though so I think the tests need to be updated to account for that….

I have a merge request for this - which works. But it fails in php5 because verify requires php7.

If we drop support for 5 then my
PR can be merged in. Until that happens we are locked to verify 1.

**Comment by TavoNiievez** [comment]
I edited my commit to make it co-authored. I will keep this PR open.

**Comment by developedsoftware** [comment]
@TavoNiievez https://github.com/yiisoft/yii2-app-advanced/pull/521

**Pull request closed without merging**
