### PR TITLE
Use application name instead of string literal in the copyright footer line

### PR DESCRIPTION
**Pull request by kanekesreal**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | nothing

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by kanekesreal** [comment]
thanks. it my firsttime to contibute open source. 
i have problem with continuous-integration/travis-ci/pr always failed. what should i do before making pull request?

**Comment by cebe** [comment]
there is a test that verifies that "My Company" is a string that is available on the page, which now obviously fails: https://travis-ci.org/yiisoft/yii2-app-advanced/jobs/282055099#L1130

**Comment by samdark** [comment]
Already done https://github.com/yiisoft/yii2-app-advanced/commit/6b0de8bd2d733f1887a8bbf8c17da34d4f03b421

**Comment by kanekesreal** [comment]
what should i learn to do that?
if i tested my code with testing unit, is CI will be no fail?
i never use testing with test unit.
and sorry if my english is bad :)

**Comment by kanekesreal** [comment]
@samdark I've seen your code at [6b0de8b](https://github.com/yiisoft/yii2-app-advanced/commit/6b0de8bd2d733f1887a8bbf8c17da34d4f03b421) and I feel a bit about it about unit testing.

**Comment by samdark** [comment]
Check docs on testing.

**Pull request merged**
