### PR TITLE
Add set owner and group feature to the init script

### PR DESCRIPTION
**Pull request by galkindev**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | add setOwnerAndGroup feature to the init script;

### CODE REVIEW

**Comment by samdark** [comment]
Makes sense to me. @yiisoft/core-developers what do you think?

**Comment by cebe** [comment]
yep, looks good to me

**Comment by rob006** [comment]
Only root can change owner of a file. Does this mean that I have to run init as root?

**Comment by cebe** [comment]
if you want to use this feature then yes, its not enabled by default but makes sense when deploying on a server imo.

**Comment by rob006** [comment]
But what is a point of that? chmod 0777 isn't enough?

**Comment by cebe** [comment]
chmod 0777 is insecure, it's better to have 0775 or even 0770 and proper ownerships.

**Comment by rob006** [comment]
@cebe Running init as root will set root as a owner of all files copied from `environments`. If someone use suPHP, application will run as root. It is much more insecure than 777 for upload or logs directory.

**Comment by galkindev** [comment]
@rob006 yes, you are right, this is might be a problem.

**Pull request closed without merging**
