### PR TITLE
move fixtures (common) to test folder

### PR DESCRIPTION
**Pull request by bscheshirwork**
Fixtures can be inside test folder IMHO

let's discuss!

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes/no
| Breaks BC?    | YES: any other (user-defined) fixtures can be moved manually 
| Tests pass?   | yes

### CODE REVIEW

**Comment by bscheshirwork** [comment]
also I don't find any standard how select name of folder

**Comment by samdark** [comment]
Fixtures could be executed without tests to fill database with data for development purposes.

**Comment by bscheshirwork** [comment]
Agree. Any another opinions?

**Comment by samdark** [comment]
Leave it as is.

**Pull request closed without merging**
