### PR TITLE
Set en language in test

### PR DESCRIPTION
**Pull request by githubjeka**
Like here https://github.com/yiisoft/yii2-app-basic/pull/9

### CODE REVIEW

**Comment by samdark** [comment]
Isn't it a default value?

**Comment by githubjeka** [comment]
Yes
https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L111

**Comment by cebe** [comment]
@samdark yes, but this avoids breaking the tests, when language changes, see yiisoft/yii2-app-basic#9

**Comment by cebe** [comment]
Thanks!

**Pull request merged**
