### PR TITLE
init script: improved error handling, output stylization.

### PR DESCRIPTION
**Pull request by dmitry-kulikov**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | no

Improves error handling in _init_ script, for example _init_ didn't show error message if chmod execution failed.
Adds stylization to output of _init_ script, right now only red color for error messages. Frankly speaking I don't like how file grew, probably this script does too many things now.
Breaks backward compatibility: if for some reason someone used `setExecutable` for directories then it won't work anymore.

### CODE REVIEW

**Comment by samdark** [comment]
What's the reason to break compatibility?

**Comment by dmitry-kulikov** [comment]
Now `setExecutable` can be used for directories again, should be compatible with previous version.

**Comment by samdark** [comment]
Thanks. Will review it soon.

**Comment by samdark** [comment]
Thank you! Merged and made some adjustments: https://github.com/yiisoft/yii2-app-advanced/commit/8aba5059234233f676e553ac5200ab455c6197bf

**Pull request closed without merging**
