### PR TITLE
Add .env file

### PR DESCRIPTION
**Pull request by sheillendra**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2/issues/13602

### CODE REVIEW

**Comment by rob006** [comment]
What is the point of having `env-dev` and `env-prod`?

**Comment by sheillendra** [comment]
> What is the point of having `env-dev` and `env-prod`?
To ensure the `.env` file that has been prepared is in accordance with the selected `init`. Because it does not override the possibility before it is uploaded to the prod server, the server will first try on dev. In addition to minimizing the polemic if the .env file is a docker setting

**Comment by sheillendra** [comment]
> What is the point of having `env-dev` and `env-prod`?

Because Yii2 already has a `dev` and `prod` environment, it's a pity if we don't use it.

**Comment by rob006** [comment]
> Because Yii2 already has a `dev` and `prod` environment, it's a pity if we don't use it.

`.env` file is for local config, it is not specific for prod or dev environment. Why would you need multiple local configs?

**Comment by sheillendra** [comment]
The `.env` file contains confidential data, and is manually uploaded to the server without going through `git`, this makes it easy without having to change the file name or contents, besides minimizing human errors. I think it will be very troublesome if the same application is used in many servers. And we know that the data from the `dev` and` prod` configurations are different.

**Comment by sheillendra** [comment]
For example on my local computer, two '.env' files have been prepared for `dev` and 'prod' and to distinguish them, I name it` .env-dev` and `.env-prod`. After the application is installed, I manually upload the two files, and I easily do init for any environment without changing the file '.env'

**Comment by samdark** [comment]
It is not recommended to use .env for anything other than local development. In a real server real OS environment variables are used instead.

**Comment by samdark** [comment]
Thank you for contribution but I don't think we should add .env to Yii 2 application templates.

**Pull request closed without merging**
