### PR TITLE
up yiisoft/yii2-swiftmailer

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #296

### CODE REVIEW

**Comment by cebe** [comment]
the app template still works on PHP 5.4, this change will break that compatibility, so it can only be merged in 2.1.0

**Comment by rob006** [comment]
`~2.0.0 || ~2.1.0`

**Comment by bscheshirwork** [comment]
@rob006 the new version of swiftmailer/swiftmailer 2.1.x requred php ^7.0.0

**Comment by rob006** [comment]
@bscheshirwork This allows to install any of this two version, and composer will choose best. If you have PHP 5 - 2.0 will be installed. On PHP 7 you will get 2.1.

**Comment by bscheshirwork** [comment]
Nice!
@cebe what you think?

**Comment by cebe** [comment]
good suggestion @rob006 ! @bscheshirwork fine with me,

**Comment by cebe** [comment]
Thanks!

**Pull request merged**
