### PR TITLE
Use separated file for merge test config

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | #360 #348

### CODE REVIEW

**Comment by samdark** [comment]
Why?

**Comment by bscheshirwork** [comment]
Fix a codeception tests

**Comment by SilverFire** [comment]
It looks too complex. I think it can be solved in easier way

**Comment by bscheshirwork** [comment]
i.e. need separate from merging config? (create another independence issue)?

In this moment codeception config file is broken on branch master.

**Comment by Faryshta** [comment]
Closed in favor of #377

**Pull request closed without merging**
