### PR TITLE
Add InitDbFixture to FixtureHelper

### PR DESCRIPTION
**Pull request by daniel-mc**
Suggestion to address #26

### CODE REVIEW

**Comment by samdark** [comment]
@Ragazzo you've asked for a pull request.

**Comment by Ragazzo** [comment]
I am fine with it, @daniel-mc did you test it? If it is ok, then merge it

**Comment by daniel-mc** [comment]
Yes, the tests pass and I'm using it in my current project like this.

**Comment by Ragazzo** [comment]
Ok

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
