### PR TITLE
Update start-installation.md

### PR DESCRIPTION
**Pull request by thiagotalma**
Include instruction for hosts file

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/07245998dff81f73c784a8830b9d8a5507292823

**Comment by thiagotalma** [comment]
@samdark I found it strange that GitHub changed the numbering of the item.
I inserted 5, but is being displayed 1.

You know how to fix?

**Comment by samdark** [comment]
That's markdown. It's better to use unordered list in this case or remove list at all.

**Comment by cebe** [comment]
if you use correct indentation for the list, it will be displayed correctly.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/9ea6e0009f3d9603977b64d1c7f6a028ffdc5d9d

**Comment by cebe** [comment]
note that the github markdown renderer has some weird bugs. The file renders fine on the apidoc generator.

**Comment by thiagotalma** [comment]
@cebe , the formatting was not good. Take a look at the example of the Nginx configuration file.

**Comment by cebe** [comment]
thats what I meant with this:

> note that the github markdown renderer has some weird bugs. The file renders fine on the apidoc generator.

**Comment by thiagotalma** [comment]
:+1:

**Pull request closed without merging**
