### PR TITLE
Updated Vagrant box

### PR DESCRIPTION
**Pull request by ElisDN**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by thiagotalma** [comment]
@samdark This is not good...  😕 

This version is not LTS.
It will probably not be used on a production server. Ideally the dev environment should be as close to the prod.

**Comment by cebe** [comment]
good point, but this is a template, you need to adjust your Vagrant setup to the production env anyway and in that progress you can change the image to whatever runs on your production server.

**Comment by ElisDN** [comment]
Hm... Yes, it is really not LTS. @samdark, revert the commit please.

**Comment by samdark** [comment]
@ElisDN done.

**Comment by thiagotalma** [comment]
@cebe certainly neither you nor I will use this template. However, unfortunately we know that less experienced developers will structure an app using this template and may experience problems when they are sent to production 😉

**Pull request merged**
