### PR TITLE
:copyright: Remove notice

### PR DESCRIPTION
**Pull request by githubjeka**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

Asset files has many changes by times and copyright needs to pull all time by BSD. Can you remove it?
@qiangxue :gift_heart:

### CODE REVIEW

**Comment by qiangxue** [comment]
Looks good to me. @yiisoft/core-developers What's your thought? I think we can remove all similar copyright notice (if any) from other template files like this.

**Comment by samdark** [comment]
Yes. These are part of the app and belong to user after being installed.

**Comment by cebe** [comment]
Makes sense.

**Comment by samdark** [comment]
Merged. Thanks @githubjeka!

**Pull request merged**
