### PR TITLE
Minor  changes to remove deprecation messages

### PR DESCRIPTION
**Pull request by RichardPillay**
| Q             | A
| ------------- | ---
| Is bugfix?    | Future Proofing
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Changed codeception.yml files to move the bootstrap setting out of the Settings section.

### CODE REVIEW

**Comment by Naktibalda** [comment]
Failing test would pass now.

**Comment by samdark** [comment]
Restarted build.

**Comment by Naktibalda** [comment]
@samdark no, you didn't.

**Comment by rob006** [comment]
Restarted, it is fine now.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
