### PR TITLE
Added ability to run 'init --env=dev'

### PR DESCRIPTION
**Pull request by hiqsol**
There are no tests for init. Right?

### CODE REVIEW

**Comment by samdark** [comment]
No. There are no tests. I don't think it's a good idea to use directory names like that.

**Comment by LAV45** [comment]
What is if just rename https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/index.php#L32 in a prod ?

**Comment by samdark** [comment]
Yes, that would be better solution to rename it to use key and add title for display purposes.

**Comment by samdark** [comment]
Or just rename it.

**Pull request closed without merging**
