### PR TITLE
added minimal Docker setup

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | there are none
| Fixed issues  | #214, #244 

Related: https://github.com/yiisoft/yii2-docker/issues/28#issuecomment-371098356, https://github.com/yiisoft/yii2-app-advanced/pull/250

### CODE REVIEW

**Comment by sazo** [comment]
Its simple and achieves the same as #250 👍 

What is the reason the db is not included and only in the guide?

IMO the jwilder/nginx-proxy:alpine container is really nice - because when redirecting between frontend and backend i dont think it will redirect to the right port? correct me if im wrong. 

Otherwise looks good and simple 👍

**Comment by schmunk42** [comment]
> What is the reason the db is not included and only in the guide?

You could choose MySQL (Percona/MariaDB) or PostGres or SQLite or another one Yii supports; although docs could be more detailed how to use different ones; but the guide also does not cover MySQL installation and setup ie.

> IMO the jwilder/nginx-proxy:alpine container is really nice - because when redirecting between frontend and backend i dont think it will redirect to the right port? correct me if im wrong.

It serves as a proxy so it would not redirect. But there are other things to consider:
1. you need to set up hostnames or wildcard DNS (or use .localhost)
2. for the reverse proxy to make sense you should only have one for your Docker machine, which means it should be moved out of the project, which leads to a special setup for configuring Docker networks, this can be painful and error-prone. The best working out-of-the-box solution for local development (not CI) are fixed ports (a different set per project) IMHO

**Comment by schmunk42** [comment]
How should we proceed with this? I think there should be some more info about db setup.

Should we add MySQL by default or PostGres or both, or something to the docs how to do that?

Here or in the guide?

**Comment by samdark** [comment]
> I think there should be some more info about db setup.

**Comment by samdark** [comment]
> Should we add MySQL by default or PostGres or both, or something to the docs how to do that?

MySQL by default + docs about PostgreSQL

**Comment by samdark** [comment]
> Should we add MySQL by default or PostGres or both, or something to the docs how to do that?

MySQL by default + docs about PostgreSQL

**Comment by samdark** [comment]
> Here or in the guide?

Here commented out in config?

**Comment by schmunk42** [comment]
Done.

**Comment by schmunk42** [comment]
@machour nothing missing that I could remember...

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by schmunk42** [comment]
@creep3r Do you run DockerForMac, a VM with docker-machine or something else?

**Comment by creep3r** [comment]
@schmunk42 Oh yes, Im running docker-machine on virtualbox instance.

**Comment by schmunk42** [comment]
Would it work for you to give permissions to the asset-folder on the host?

**Comment by creep3r** [comment]
I did test also on native DockerForMac fresh installation.
1) this persist, because of [default yii2-docker apache vhost config](https://github.com/yiisoft/yii2-docker/blob/master/php/image-files/etc/apache2/sites-available/000-default.conf)
2) it seems to be issue related to docker-machine + virtualbox setup. perhaps could be mentioned in docs?

**Comment by billyshen26** [comment]
hi @schmunk42 ,
any advice to write a Dockerfile for console service, i want to run schedule in docker, thanks in advance.

Billy

**Comment by schmunk42** [comment]
My advice would be to run to scheduler in the same container as your web-server, eg. with `supervisord` - see https://github.com/dmstr/docker-php-yii2/blob/release/6.x/nginx/Dockerfile-fpm-nginx for an example.

Although this is not 100% Docker-one-service-per-container, we found this to be less error-prone than a separate container - which might be useful for very CPU and/or IO-heavy jobs.

Also keep in mind that you need to export your ENVs for scheduler, see https://github.com/dmstr/phd5-app/blob/master/image-files/usr/local/bin/export-env.sh for an example (it's ugly, but we haven't found anything better yet). 

We are running one cronjob once per minute which triggers the scheduler, see also https://github.com/dmstr/phd5-app/blob/master/src/config/schedule.php

**Comment by phdabel** [comment]
Hi, I worked on a docker solution for Yii2 advanced template some time ago.
I needed to work with SSL, thus the script generates self-signed certificates for testing.
It works well and from this, I worked on a new solution combined with supervisord for another application.

[https://github.com/phdabel/yii2fpm-nginx-docker]

**Pull request merged**
