### PR TITLE
Database: Seeding ability

### PR DESCRIPTION
**Pull request by githubjeka**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

Added configuration to fixtures console app.
Added a User fixture. Updated documentation and phpDoc.

### CODE REVIEW

**Comment by DavertMik** [comment]
They should be called "seeds" for not to confuse with fixtures in tests. They have same implementation but different ideas. In this case they are used to populate the initial data.

**Comment by samdark** [comment]
Agree. Seeds is a better name in this case.

**Comment by samdark** [comment]
@githubjeka could you adjust naming?

**Comment by samdark** [comment]
@githubjeka testing was heavily refactored by @DavertMik. Could you please re-check this pull request?

**Comment by githubjeka** [comment]
@samdark I can set `seeds`, but need to create a new SeedController. For tips in console that will use the term `seeds`.  I think it should be added to `yii\console\controllers\` in yii2 repo, not in here.

I can send PR to yii2-repo and rebuild this PR after

**Comment by samdark** [comment]
Yep. Would be great.

**Comment by githubjeka** [comment]
Example:
```
class SeedController extends Controller
{
    use FixtureTrait {
        //to hide fixture api
        fixtures as private;
        globalFixtures as private;
        loadFixtures as private;
        unloadFixtures as private;
        getFixtures as private;
        getFixture as private;
        createFixtures as private;
        //to rename as seed api
        fixtures as public seeds;
        globalFixtures as public globalSeeds;
        unloadFixturesas public unloadSeeds;
        loadFixtures as public loadSeeds;
        getFixtures as public getSeeds;
        getFixture as public getSeed;
        createFixtures as protected createSeeds;
    }

    public function actionLoad(array $seedsInput = [])
    {    
        //...
        $this->unloadSeeds($seedsObjects);
        $this->loadSeeds($seedsObjects);
        $this->notifyLoaded($seeds);

        return static::EXIT_CODE_NORMAL;
    }
```
It's bad.

SeedController depend on tests/fixtures classes. 
SeedComponent should be used by the SeedController. But to create SeedComponent need to create 

```
ActiveSeed.php
ArraySeed.php
BaseActiveSeed.php
DbSeed.php
Seed.php
SeedTrait.php
InitDbSeed.php
```

as `test/` namespace 
```
ActiveFixture.php
ArrayFixture.php
BaseActiveFixture.php
DbFixture.php
Fixture.php
FixtureTrait.php
InitDbFixture.php
```

Too much trouble....

**Comment by samdark** [comment]
So you're not going to work on it, correct? If not, I'll close this pull request since it can't be merged as is.

**Comment by githubjeka** [comment]
To next time...

**Pull request closed without merging**
