### PR TITLE
Update start-installation.md

### PR DESCRIPTION
**Pull request by OndrejVasicek**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  | 

If you edit directly the config in common folder, after another “init execution”, it’ll override you setting. So if I understand correctly, you should write you db connection into environment/dev folder instead and then run the “init”, which copy your environment/dev config. So after any other init, it overrides by the correct file.

### CODE REVIEW

**Comment by samdark** [comment]
It's correct initially.

**Comment by OndrejVasicek** [comment]
I don't get it then. If I execute “init” again, my settings in common folder will be lost, because it'll be overwritten. What’s the point for the whole “environment concept” then?
Thank you for the explanation.

**Comment by samdark** [comment]
Well, first of all, init script is for initializing configs. Then you may adjust `-local.php` ones directly on the server and keep your passwords etc. out of repository.

Second, it asks you if you want to overwrite files.

**Comment by OndrejVasicek** [comment]
Ok, I probably didn’t fully understand the concept of “-local” before. So please Samdark, could I share some of my thoughts, and then you tell me if I’m correct or wrong, shall we?

Let’s take some info from here https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md (btw is there any reason why the link to advanced template in guide doesn’t work?)

> Each environment is represented by a set of files under the environments directory. The init command is used to switch between these. What it really does is copy everything from the environment directory over to the root directory where all applications are.

So, this should be used when I prepare release into master branch and when I switch back to develop branch. Therefore I can easily switch all the settings and params in all the folders.
But my mistake was that I wanted to switch even the “-local” files, where for example the database connections is. And that’s wrong from two reasons:

1. “-local” files in environment aren’t in gitignore (they can’t be for obvious reasons) and they’d become a part of repository

2. I mustn’t edit “-local” files “for everyone”, because they are related to the local environment – server for example connects to localhost, at home I connect to my local database, at office I could connect to a server in company network, etc

But there was still 1 thing I thought this concept was supposed to solve, but I guess it doesn’t – what if I have different db connections for production and development? If I Ignored the two previous reasons, I could do that, but only for me – one local environment, which is obviously wrong and what I was thinking of.

So in the end I suppose I have to put a condition into my “-local” files to check what environment I’m right now and chose the correct connection for my local machine, server, work station, test server, .... Am I correct?

Thanks for your effort and your work on Yii again.

**Comment by samdark** [comment]
> btw is there any reason why the link to advanced template in guide doesn’t work?

It works.

> So, this should be used when I prepare release into master branch and when I switch back to develop branch.

No, why? `-local.php` files are never committed so there's no need to use production ones locally.

> “-local” files in environment aren’t in gitignore (they can’t be for obvious reasons) and they’d become a part of repository

Correct. These are templates.

> I mustn’t edit “-local” files “for everyone”, because they are related to the local environment – server for example connects to localhost, at home I connect to my local database, at office I could connect to a server in company network, etc

Yes. Correct. These are environment specific. If there's something "for everyone", put it into non local config.

> what if I have different db connections for production and development

What's the problem? In each of these environments you'll have these different connections in `-local.php`.

> So in the end I suppose I have to put a condition into my “-local” files to check what environment I’m right now and chose the correct connection for my local machine, server, work station, test server, .... Am I correct?

No. No need for condition.

**Comment by OndrejVasicek** [comment]
> > btw is there any reason why the link to advanced template in guide doesn’t work?
> 
> It works.

The link in the menu doesn't.

> > So, this should be used when I prepare release into master branch and when I switch back to develop branch.
> 
> No, why? -local.php files are never committed so there's no need to use production ones locally.

There is actually a reason. Let me explain. It’s not only the “-local” files which the “init” execution copies, but also index.php and index-text.php in 2 folders and yii.php.
How else should I prepare a release? I had to change somehow these two lines in 5 files
```
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```
So I meant the “init” has been made for helping here (and for the initiation), because you write it

> The init command is used to switch between these. (environments)

Maybe I should clarify what my workflow is. Two branches in repo – dev, master. Local apache on my PC. Working on dev branch – Yii set up to dev environment. Connected to dev database on local server.

But then I prepare a release. I use git-flow. Start a release. Create changelog and other staff. Need to switch Yii to production – that’s the moment when I have to edit the two lines five-times or use the “init”. And now, in that moment, I want the system to be connected to the production database on the remote server (because Yii is set up to production). I know that there is its own “-local” config on the server, but I need to see the whole production environment from my local machine. It means different credentials.

So what should I do? Because we denied to put credentials into environment folder from good reasons, the only solution seems to be the condition in my “-local” file – check if I’m in production or in dev and chose the proper credentials. 

After that I do commit. Finish release in git-flow (which merges dev into master, ads tag, etc). Send to remote repo on server. The server deploys the master branch to actual production. “-local” on the server is used.

So what am I missing here? It looks like there is some whole in my interpretation of environment concept.

**Comment by samdark** [comment]
> The link in the menu doesn't.

Right... that's a bug: https://github.com/yiisoft/yii2-apidoc/issues/43

> How else should I prepare a release? I had to change somehow these two lines in 5 files

No. You're initializing these once and never touching it again.

> So I meant the “init” has been made for helping here (and for the initiation), because you write it

Fixed: https://github.com/yiisoft/yii2-app-advanced/commit/c8cfc738addc37c40bb828b72d64a3f6025c4d5b

> I need to see the whole production environment from my local machine

That's kinda weird... What for?

> Because we denied to put credentials into environment folder from good reasons, the only solution seems to be the condition in my “-local” file – check if I’m in production or in dev and chose the proper credentials.

In your case yes. But accessing production database from local machine isn't common and for a reason.

**Comment by OndrejVasicek** [comment]
I accept that connect to production db may be a bit strange. Condition will do then. 
My dev db is sometimes quite different, so it’s convenient to see the web with real data before push the master branch to production. Nothing serious.

> No. You're initializing these once and never touching it again.

That’s the last thing I don’t understand. I initialize the Yii to develop, because I start work in dev branch. But the files which sett YII_DEBUG and YII_ENV are in repo. I have to change them before merge them into master, because master will appear on production.

**Comment by samdark** [comment]
> My dev db is sometimes quite different, so it’s convenient to see the web with real data before push the master branch to production. Nothing serious.

Could lead to unforeseen consequences :)

> But the files which sett YII_DEBUG and YII_ENV are in repo.

No, they are not. `index.php` in excluded via `.gitignore`.

**Comment by OndrejVasicek** [comment]
Oh dear… I’m really sorry. I overwrote the gitignore in my frontpage folder by a frontend FW I’m using. So the index.php and index-test.php wasn’t “grey” in PHPStorm anymore. My bad.
So everything is clear now. Thank you for your answers and time.

**Comment by samdark** [comment]
One thing... I still suspect it's not clear enough in the docs. Would be totally awesome if you'll re-read docs and check if anything contradicts what I've said here. Thanks!

**Comment by OndrejVasicek** [comment]
I went through every chapter of Advanced Template docs and didn’t find any factual errors. But I found some places, which in my opinion could be more expressive. But it can be just my poor experiences or low level of English. The fact is, that Yii2 is many times a place, where I learn new stuff. So It’s not a bad idea to be sometimes more open and let people absorb your knowledge.

Here are my notes anyway. I’ll be glad if they help, no stress if they don’t.

* https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md
  * Here you use url like frontend.dev and backend.dev. In know it’s just an example, but people usually work on more apps. So I made my own version for httpd.conf
    ```
    <VirtualHost *:80>
        ServerAlias *.dev
        RewriteEngine on

        RewriteCond %{HTTP_HOST} ^(([^\.]+)\.)?([^\.]+)\.dev
        RewriteCond C:/Path-to-my-projects-folder/%3/%2/ -d
        RewriteRule ^(.*) /%3/%2/$1 [L]
    </VirtualHost>
    ```
    which accepts url like front.yii-app1.dev/rest-of-the-url. By using symlink I can easily target it to “frontend/www” folder in my yii project. Works like a charm, even for url like different-web.dev

  * > Otherwise, in production execute init in non-interactive mode

    I don’t understand why in non-interactive mode. Maybe there could be more information about putting stuff on server. If copy them or just run some script.
* https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-directories.md
  
  I feel that more information about purpose of these folders wouldn’t hurt or just include some links like init and composer have.
* https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-applications.md
  
  My first idea was – ok, great, but what’s the difference between this applications (front, backand) and module? From docs I know that module is something like “mini-application”, but this is also quite vague. Is there something, which makes an application to be the application and a module to be the module? The administration it’s quite clear – it has it’s own everything, except the shared modules. But the rest is not so clear. Even you example with blog isn’t so clear to me. If blog has the same layout, I could easily imagine it like a module.
Let’s say I have regular web presentation. Then I want to add forum, blog and shop. What should be an application and what just a module and mainly “why”.
* https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md
  
  This is the most crucial part. It’s good theory, but how I’ve just experienced, there is a big gap between theory and human’s brain. Examples are the best glue to stick them together. They are really missing there. It would be nice to have a real-life situation with personal computer, colleagues’ computer, production server and for example test server. Then step by step show what to do. As I said in the beginning – it’s great to learn some “good habits”.
* https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-link-backend-frontend.md
  
  Isn’t it against the DRY? Or you didn’t mean duplicate but include from the frontend?

**Comment by samdark** [comment]
Applied some of your suggestions. Thank you!

**Pull request closed without merging**
